import Head from "next/head";
import React from "react";
import { getProviders, signIn } from "next-auth/react";
import Image from "next/image";

const login = ({ providers }) => {
  console.log(providers);
  return (
    <div className="flex flex-col items-center justify-center bg-black min-h-screen w-full">
      <Head>
        <title>Log in - Spotify 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src="https://links.papareact.com/9xl"
        width={100}
        height={100}
        alt="logo"
      />
      {Object.values(providers).map((provider) => (
        <div key={provider.id}>
          <button
            className="bg-[#18D860] text-white rounded-full p-3 mt-3"
            onClick={() => signIn(provider.id, { callbackUrl: "/" })}
          >
            Login with {provider.name}
          </button>
        </div>
      ))}
    </div>
  );
};

export default login;

export async function getServerSideProps() {
  const providers = await getProviders();
  return {
    props: {
      providers,
    },
  };
}
